### ISSUE TITLE
Hex color is broken 

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#14]
After updating to `1.3.3` color in some classes has become broken after renaming:
```css
.HeaderMenu_item {
    color: #b6c5cc
}
.HeaderMenu_item:focus {
    color: #dfe7ed;
    background-color: #202839
}
.HeaderMenu_item:focus .HeaderMenu_itemContent {
    border-left-color: #00f4f5
}
```
Renamed into
```css
.lm {
    color: #or
}
.lm:focus {
    color: #dfe7ed;
    background-color: #202839
}
.lm:focus .lg {
    border-left-color: #00f4f5
}
```
