### ISSUE TITLE
Messes up with the `~` character

### ISSUE THREAD

**Issue by atishay** [JPeer264/node-rename-css-selectors#48]
When we have a css like this:
```css
.test,
.test~.icon {
display: none;
}
```
In the mapping, it generates:

```
".test": "a",
".test~":, "b"
```
