### ISSUE TITLE
Ignore specific class

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rename-css-selectors#62]
Hi!

I'm using css modules, and have cases when I use `:global()` selector to keep classname inside it untouched by the css modules naming algorithm.
It's useful when local modules want to style some third party libraries. In this example, tippy.js:
```css
.tooltip[data-placement^='top'] > :global(.tippy-arrow) {
  bottom: var(--arrow-offset);
  border-top-color: var(--tooltip-bg-color);
}
```
which will be converted by css modules let's say into this
```css
.MyComponent_tooltip[data-placement^='top'] > .tippy-arrow {
  bottom: var(--arrow-offset);
  border-top-color: var(--tooltip-bg-color);
}
```

So `.tippy-arrow` classname stays untouched. And element with that classname is produced by the third party tippy.js library, that's why I want to keep it untouched, I don't want to mangle it.

But then `rcs.process.auto` does rename `.tippy-arrow` classname anyway, so selector stops matching the element `<div class="tippy-arrow">`

```css
.a[data-placement^='top'] > .b{
  bottom: var(--arrow-offset);
  border-top-color: var(--tooltip-bg-color);
}
```

Is there a way to ignore specific classnames?
